# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 303ba93d8b20c25bbd1e59b341fe86bdfcf1daa329158fceedde35cad67d420b7386a29a276ec93b2edd85570b4ba9b73e68bc50f1d2d0ce5b5c7a5f6c02d9b4

test:
  secret_key_base: e749638956c18ef484505c2b2986f7cb438af8c34a93efe4cdbf8536aca5933d5d6f9d7eb500924e0fc79785bd7252126f0f275f509196585f1e65bf7f0874d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
